name: Release

# Controls when the workflow will run
# OpenBLAS is disabled for now
# Schedule doesn't accept inputs. So, this has hardcoded values for repository / branch
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create_release:
    name: Create Release
    uses: ./.github/workflows/release.yml
    with:
      blass_type: 'apl'
      pytorch_repository: 'iremyux/pytorch'
      pytorch_branch: 'apl-tests'
      wheel_name: 'torch-2.4.0a-cp311-cp311-win_arm64.whl'
      release_prefix: 'Daily Release'