# Daily Sync workflow draft for PyTorch's daily code.
# Workflow file is created with dummy values for main branch (so we can use it with different branch while working)

name: Daily Sync

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Dummy value"
        required: false
        default: false
        type: boolean

env:
  SCRIPTS_DIR: ${{ github.workspace }}\pytorch-job\workflow\.github\scripts
  JOB_DIR: ${{ github.workspace }}\pytorch-job
  DOWNLOADS_DIR: ${{ github.workspace }}\pytorch-job\downloads
  DEPENDENCIES_DIR: ${{ github.workspace }}\pytorch-job\dependencies

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Windows, ARM64, PYTORCH]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git checkout workflow
        uses: actions/checkout@v4
        with:
          path: ${{ env.JOB_DIR }}/workflow
      - name: Bootstrap APL
        run: |
          & ${{ env.SCRIPTS_DIR }}\bootstrap_apl.bat