# Daily Sync workflow draft for PyTorch's daily code.
# Workflow file is created with dummy values for main branch (so we can use it with different branch while working)

name: Daily Sync

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Dummy value"
        required: false
        default: false
        type: boolean

env:
  JOB_DIR: ${{ github.workspace }}\pytorch-job
  DOWNLOADS_DIR: ${{ github.workspace }}\pytorch-job\downloads
  DEPENDENCIES_DIR: ${{ github.workspace }}\pytorch-job\dependencies
  SCRIPTS_DIR: ${{ github.workspace }}\pytorch-job\workflow\.github\scripts
  PYTORCH_SOURCES_DIR:  ${{ github.workspace }}\pytorch-job\src\${{ inputs.pytorch_repository }}\${{ inputs.pytorch_branch }}
  WHEEL_DIR: ${{ github.workspace }}\pytorch-job\src\${{ inputs.pytorch_repository }}\${{ inputs.pytorch_branch }}\dist
  WHEEL_NAME: ${{ inputs.wheel_name }}
  ENABLE_BUILD_WHEEL: 1
  ENABLE_APL: ${{ inputs.blas_type == 'apl' && '1' || '0' }}
  ENABLE_OPENBLAS: ${{ (inputs.blas_type == 'openblas' || inputs.blas_type == 'openblas_clang') && '1' || '0' }}
  DEPENDENCY_SCCACHE_DIR: ${{ github.workspace }}\pytorch-job\dependencies\sccache
  DEPENDENCY_APL_DIR: ${{ github.workspace }}\pytorch-job\dependencies\apl\armpl_24.04\bin
  DEPENDENCY_OPENBLAS_DIR: ${{ github.workspace }}\pytorch-job\dependencies\openblas

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Windows, ARM64, PYTORCH]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Bootstrap Ninja
        run: |
          & ${{ env.SCRIPTS_DIR }}\bootstrap_ninja.bat
      - name: Bootstrap Buildtools
        run: |
          & ${{ env.SCRIPTS_DIR }}\bootstrap_buildtools.bat
      