name: Release

# Controls when the workflow will run
# OpenBLAS is disabled for now
# Schedule doesn't accept inputs. So, this has hardcoded values for repository / branch
on:
  schedule:
    - cron: "0 0 * * *"

  # just for testing.
  workflow_dispatch:
    inputs:
      wheel_name:
        description: "Release wheel name (should be compatible with wheel syntax)"
        required: true
        default: "torch-2.4.0a-cp311-cp311-win_arm64.whl"
        type: string
env:
  BLASS_TYPE: 'apl'
  PYTORCH_REPOSITORY: iremyux\pytorch
  PYTORCH_BRANCH: apl-tests
  JOB_DIR: ${{ github.workspace }}\pytorch-job
  DOWNLOADS_DIR: ${{ github.workspace }}\pytorch-job\downloads
  DEPENDENCIES_DIR: ${{ github.workspace }}\pytorch-job\dependencies
  SCRIPTS_DIR: ${{ github.workspace }}\pytorch-job\workflow\.github\scripts
  PYTORCH_SOURCES_DIR:  ${{ github.workspace }}\pytorch-job\src\iremyux\pytorch\apl-tests
  WHEEL_DIR: ${{ github.workspace }}\pytorch-job\src\iremyux\pytorch\apl-tests\dist
  WHEEL_NAME: torch-2.4.0a-cp311-cp311-win_arm64.whl
  ENABLE_BUILD_WHEEL: 1
  DEPENDENCY_SCCACHE_DIR: C:\_WORK\dependencies\sccache
  DEPENDENCY_APL_DIR: C:\_WORK\dependencies\apl\armpl_24.04\bin
  RELEASE_PREFIX: Daily Release

jobs:
  create_release:
    name: Create Release
    runs-on: [self-hosted, Windows, ARM64, PYTORCH]
    timeout-minutes: 800
    uses: ./.github/workflows/release.yml
    with:
      blass_type: ${{ env.BLASS_TYPE }}
      pytorch_repository: ${{ env.PYTORCH_REPOSITORY }}
      pytorch_branch: ${{ env.PYTORCH_BRANCH }}
      wheel_name: ${{ env.WHEEL_NAME }}