name: Daily Release

# Controls when the workflow will run
# Schedule doesn't accept inputs. So, this has hardcoded values for repository / branch
on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  create_release_apl:
    name: Create Release with APL
    uses: ./.github/workflows/release.yml
    with:
      blas_type: 'apl'
      pytorch_repository: 'iremyux\pytorch'
      pytorch_branch: 'apl-tests'
      wheel_name: 'torch-2.4.0a-cp311-cp311-win_arm64.whl'
      release_prefix: 'Daily Release - APL'
  create_release_openblas:
    name: Create Release with OpenBLAS
    uses: ./.github/workflows/release.yml
    with:
      blas_type: 'openblas'
      pytorch_repository: 'iremyux\pytorch'
      pytorch_branch: 'apl-tests'
      wheel_name: 'torch-2.4.0a-cp311-cp311-win_arm64.whl'
      release_prefix: 'Daily Release - OpenBLAS'