name: Release

# Controls when the workflow will run
# OpenBLAS is disabled for now
on:
  # for manual releases
  workflow_dispatch:
    inputs:
      blass_type:
        description: "Choose BLAS type (for now only APL)"
        required: true
        default: 'apl'
        type: choice
        options:
          - apl
      pytorch_repository:
        description: "PyTorch repository"
        required: true
        default: "iremyux/pytorch"
        type: string
      pytorch_branch:
        description: "PyTorch branch"
        required: true
        default: "apl-tests"
        type: string
      wheel_name:
        description: "Release wheel name (should be compatible with wheel syntax)"
        required: true
        default: "torch-2.4.0a-cp311-cp311-win_arm64.whl"
        type: string
      release_prefix:
        description: "Release prefix for releases page"
        required: true
        default: "Manual Release"
        type: string
    
  # for daily releases
  workflow_call:
    inputs:
      blass_type:
        type: string
      pytorch_repository:
        type: string
      pytorch_branch:
        type: string
      wheel_name:
        type: string
      release_prefix:
        type: string

env:
  JOB_DIR: ${{ github.workspace }}\pytorch-job
  DOWNLOADS_DIR: ${{ github.workspace }}\pytorch-job\downloads
  DEPENDENCIES_DIR: ${{ github.workspace }}\pytorch-job\dependencies
  SCRIPTS_DIR: ${{ github.workspace }}\pytorch-job\workflow\.github\scripts
  PYTORCH_SOURCES_DIR:  ${{ github.workspace }}\pytorch-job\src\${{ inputs.pytorch_repository }}\${{ inputs.pytorch_branch }}
  WHEEL_DIR: ${{ github.workspace }}\pytorch-job\src\${{ inputs.pytorch_repository }}\${{ inputs.pytorch_branch }}\dist
  WHEEL_NAME: ${{ inputs.wheel_name }}
  ENABLE_BUILD_WHEEL: 1
  ENABLE_APL: ${{ inputs.blass_type == 'apl' && '1' || '0' }}
  DEPENDENCY_SCCACHE_DIR: C:\_WORK\dependencies\sccache
  DEPENDENCY_APL_DIR: C:\_WORK\dependencies\apl\armpl_24.04\bin

jobs:
  create_release:
    name: Create Release
    runs-on: [self-hosted, Windows, ARM64, PYTORCH]
    timeout-minutes: 800
    steps:
      - name: Get Release Version
        run: echo "RELEASE_VERSION=v0.0.$(Get-Date -Format 'yyMMddHHmm')" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
      - name: Git checkout workflow
        uses: actions/checkout@v4
        with:
          path: ${{ env.JOB_DIR }}/workflow
      - name: Git checkout PyTorch
        uses: actions/checkout@v4
        with:
          repository:  ${{ inputs.pytorch_repository }}
          ref: ${{ inputs.pytorch_branch }}
          path: ${{ env.PYTORCH_SOURCES_DIR }}
          submodules: recursive
      - name: Clean PyTorch
        run: |
          & ${{ env.SCRIPTS_DIR }}\bootstrap_pytorch.bat
      - name: Build PyTorch
        run: |
          & ${{ env.SCRIPTS_DIR }}\build_pytorch.bat
      - name: Bootstrap PyTorch tests
        run: |
          & ${{ env.SCRIPTS_DIR }}\bootstrap_tests.bat      
      - name: Run core tests
        run: |
          & ${{ env.SCRIPTS_DIR }}\test_core.bat 1
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: ${{ env.PYTORCH_SOURCES_DIR }}\test\test-reports\*
          retention-days: 7
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ inputs.release_prefix }} - ${{ env.RELEASE_VERSION }}
          body: 'PyTorch release wheel for Windows on ARM64 (cpu-only) (RelWithDebInfo)'
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.WHEEL_DIR }}\${{ env.WHEEL_NAME }}
          asset_name: ${{ env.WHEEL_NAME }}
          asset_content_type: application/zip