name: Release

# Controls when the workflow will run

on:
  # for manual releases
  workflow_dispatch:
    inputs:
      blas_type:
        description: "Choose BLAS type"
        required: true
        default: 'apl'
        type: choice
        options:
          - apl
          - openblas
      pytorch_repository:
        description: "PyTorch repository"
        required: true
        default: "iremyux/pytorch"
        type: string
      pytorch_branch:
        description: "PyTorch branch"
        required: true
        default: "apl-tests"
        type: string
      wheel_name:
        description: "Release wheel name (should be compatible with wheel syntax)"
        required: true
        default: "torch-2.4.0a-cp311-cp311-win_arm64.whl"
        type: string
      release_prefix:
        description: "Release prefix for releases page"
        required: true
        default: "Manual Release"
        type: string
    
  # for daily releases
  workflow_call:
    inputs:
      blas_type:
        type: string
      pytorch_repository:
        type: string
      pytorch_branch:
        type: string
      wheel_name:
        type: string
      release_prefix:
        type: string

env:
  JOB_DIR: ${{ github.workspace }}\pytorch-job
  DOWNLOADS_DIR: ${{ github.workspace }}\pytorch-job\downloads
  DEPENDENCIES_DIR: ${{ github.workspace }}\pytorch-job\dependencies
  SCRIPTS_DIR: ${{ github.workspace }}\pytorch-job\workflow\.github\scripts
  PYTORCH_SOURCES_DIR:  ${{ github.workspace }}\pytorch-job\src\${{ inputs.pytorch_repository }}\${{ inputs.pytorch_branch }}
  WHEEL_DIR: ${{ github.workspace }}\pytorch-job\src\${{ inputs.pytorch_repository }}\${{ inputs.pytorch_branch }}\dist
  WHEEL_NAME: ${{ inputs.wheel_name }}
  ENABLE_BUILD_WHEEL: 1
  ENABLE_APL: ${{ inputs.blas_type == 'apl' && '1' || '0' }}
  ENABLE_OPENBLAS: ${{ (inputs.blas_type == 'openblas' || inputs.blas_type == 'openblas_clang') && '1' || '0' }}
  DEPENDENCY_SCCACHE_DIR: ${{ github.workspace }}\pytorch-job\dependencies\sccache
  DEPENDENCY_APL_DIR: ${{ github.workspace }}\pytorch-job\dependencies\apl\armpl_24.04\bin
  DEPENDENCY_OPENBLAS_DIR: ${{ github.workspace }}\pytorch-job\dependencies\openblas

jobs:
  create_release:
    name: Create Release
    runs-on: [self-hosted, Windows, ARM64, PYTORCH]
    timeout-minutes: 800
    steps:
      - name: Bootstrap APL
        run: |
          & ${{ env.SCRIPTS_DIR }}\bootstrap_apl.bat
