name: Build and run tests

on:
  workflow_dispatch:
    inputs:
      openblas_repository:
        description: "OpenBLAS repository"
        required: true
        default: "xianyi/OpenBLAS"
        type: string
      openblas_branch:
        description: "OpenBLAS branch"
        required: true
        default: "release-0.3.0"
        type: string
      blass_type:
        description: "0-Don't use blas.1-build OpenBLAS with MSVC. 2-build OpenBLAS with CLANG. 3-use APL"
        required: false
        default: 0
        type: number
      build_pytorch:
        description: "Build PyTorch"
        required: false
        default: false
        type: boolean
      run_tests:
        description: "Run tests"
        required: false
        default: false
        type: boolean
      run_tests_suite:
        description: "Test suite to run"
        required: false
        default: ""
        type: string
      run_tests_filter:
        description: "Test filter to run"
        required: false
        default: ""
        type: string
      run_tests_runs:
        description: "Test runs to execute"
        required: true
        default: 1
        type: number

env:
  JOB_DIR: ${{ github.workspace }}\pytorch-unit-tests
  SCRIPTS_DIR: ${{ github.workspace }}\pytorch-unit-tests\workflow\.github\scripts
  ENABLE_OPENBLAS: ${{ (inputs.blass_type == 1 || inputs.blass_type == 2) && '1' || '0' }}
  ENABLE_APL: ${{ inputs.blass_type == 3 && '1' || '0' }}

jobs:

  build_and_test:
    name: Build and run tests
    runs-on: [self-hosted, Windows, ARM64, PYTORCH]
    timeout-minutes: 800
    steps:
      - name: Git checkout workflow
        uses: actions/checkout@v3
        with:
          path: ${{ env.JOB_DIR }}/workflow
      - name: Git checkout OpenBLAS
        if: ${{ inputs.blass_type == 1 || inputs.blass_type == 2 }}
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.openblas_repository }}
          ref: ${{ inputs.openblas_branch }}
          path: ${{ env.JOB_DIR }}/openblas
          submodules: recursive
      - name: Git checkout PyTorch
        if: ${{ inputs.build_pytorch || inputs.run_tests }}
        uses: actions/checkout@v3
        with:
          repository: "iremyux/pytorch"
          ref: "run-test-apl-results"
          path: ${{ env.JOB_DIR }}/pytorch
          submodules: recursive
      - name: Bootstrap OpenBLAS build
        if: ${{ inputs.blass_type == 1 || inputs.blass_type == 2 }}
        run: |
          & ${{ env.SCRIPTS_DIR }}\bootstrap_openblas.bat
      - name: Bootstrap APL binaries
        if: ${{ inputs.blass_type == 3}}
        run: |
          & ${{ env.SCRIPTS_DIR }}\bootstrap_APL_24.04.bat
      - name: Bootstrap PyTorch build
        if: ${{ inputs.build_pytorch }}
        run: |
          & ${{ env.SCRIPTS_DIR }}\bootstrap_pytorch.bat
      - name: Bootstrap PyTorch tests
        if: ${{ inputs.run_tests }}
        run: |
          & ${{ env.SCRIPTS_DIR }}\bootstrap_tests.bat
      - name: Build OpenBLAS with MSVC
        if: ${{ inputs.blass_type == 1}}
        run: |
          & ${{ env.SCRIPTS_DIR }}\build_openblas_msvc.bat
      - name: Build OpenBLAS with Clang
        if: ${{ inputs.blass_type == 2}}
        run: |
          & ${{ env.SCRIPTS_DIR }}\build_openblas_clang.bat
      - name: Archive OpenBLAS
        if: ${{ inputs.blass_type == 1 || inputs.blass_type == 2 }}
        uses: actions/upload-artifact@v3
        with:
          name: openblas
          path: ${{ env.JOB_DIR }}/openblas/install/*
          retention-days: 3
      - name: Build PyTorch
        if: ${{ inputs.build_pytorch }}
        run: |
          & ${{ env.SCRIPTS_DIR }}\build_pytorch.bat
      - name: Archive PyTorch
        if: ${{ inputs.build_pytorch }}
        uses: actions/upload-artifact@v3
        with:
          name: pytorch
          path: ${{ env.JOB_DIR }}/pytorch/install/*
          retention-days: 3
      - name: Run tests
        if: ${{ inputs.run_tests }}
        run: |
          & ${{ env.SCRIPTS_DIR }}\test.bat ${{ inputs.run_tests_runs}} ${{ inputs.run_tests_suite }} ${{ inputs.run_tests_filter }}
      - name: Archive test resutls
        if: ${{ always() && inputs.run_tests }}
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: ${{ env.JOB_DIR }}/pytorch/test/test-reports/*
          retention-days: 7
