name: Build and run tests

on:
  workflow_dispatch:
    inputs:
      openblas_repository:
        description: "OpenBLAS repository"
        required: true
        default: "Blackhex/OpenBLAS"
        type: string
      openblas_branch:
        description: "OpenBLAS branch"
        required: true
        default: "fix-arm64-cross-build"
        type: string
      build_openblas_msvc:
        description: "Build OpenBLAS with MSVC"
        required: false
        default: false
        type: boolean
      build_openblas_clang:
        description: "Build OpenBLAS with Clang"
        required: false
        default: false
        type: boolean
      build_pytorch:
        description: "Build PyTorch"
        required: false
        default: false
        type: boolean
      run_tests:
        description: "Run tests"
        required: false
        default: false
        type: boolean
      run_tests_suite:
        description: "Test suite to run"
        required: false
        default: ""
        type: string
      run_tests_filter:
        description: "Test filter to run"
        required: false
        default: ""
        type: string
      run_tests_runs:
        description: "Test runs to execute"
        required: true
        default: 1
        type: number

env:
  JOB_DIR: ${{ github.workspace }}\pytorch-unit-tests
  SCRIPTS_DIR: ${{ github.workspace }}\pytorch-unit-tests\workflow\.github\scripts
  ENABLE_OPENBLAS: ${{ inputs.build_openblas_msvc || inputs.build_openblas_clang }}

jobs:
  build_openblas:
    name: Build OpenBLAS
    runs-on: [self-hosted, Windows, ARM64, PYTORCH]
    if: ${{ inputs.build_openblas_msvc || inputs.build_openblas_clang }}
    steps:
      - name: Git checkout workflow
        uses: actions/checkout@v4
        with:
          path: ${{ env.JOB_DIR }}/workflow
      - name: Git checkout OpenBLAS
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.openblas_repository }}
          ref: ${{ inputs.openblas_branch }}
          path: ${{ env.JOB_DIR }}/openblas
          submodules: recursive
      - name: Bootstrap OpenBLAS build
        run: |
          & ${{ env.SCRIPTS_DIR }}\bootstrap_openblas.bat
      - name: Build OpenBLAS with MSVC
        if: ${{ inputs.build_openblas_msvc }}
        run: |
          & ${{ env.SCRIPTS_DIR }}\build_openblas_msvc.bat
      - name: Build OpenBLAS with Clang
        if: ${{ inputs.build_openblas_clang }}
        run: |
          & ${{ env.SCRIPTS_DIR }}\build_openblas_clang.bat
      - name: Archive OpenBLAS
        uses: actions/upload-artifact@v4
        with:
          name: openblas
          path: ${{ env.JOB_DIR }}/openblas/install/*
          retention-days: 3

  build_pytorch:
    name: Build PyTorch and run tests
    needs: [build_openblas]
    runs-on: windows-latest
    timeout-minutes: 800
    steps:
      - name: Git checkout workflow
        uses: actions/checkout@v4
        with:
          path: ${{ env.JOB_DIR }}/workflow
      - name: Git checkout PyTorch
        if: ${{ inputs.build_pytorch || inputs.run_tests }}
        uses: actions/checkout@v4
        with:
          repository: "Blackhex/pytorch"
          ref: "main"
          path: ${{ env.JOB_DIR }}/pytorch
          submodules: recursive
      - name: Download OpenBLAS
        if: ${{ inputs.build_openblas_msvc || inputs.build_openblas_clang }}
        uses: actions/download-artifact@v4
        with:
          name: openblas
          path: ${{ env.JOB_DIR }}/openblas/install/
      - name: Bootstrap PyTorch build
        if: ${{ inputs.build_pytorch }}
        run: |
          & ${{ env.SCRIPTS_DIR }}\bootstrap_pytorch.bat
      - name: Bootstrap PyTorch tests
        if: ${{ inputs.run_tests }}
        run: |
          & ${{ env.SCRIPTS_DIR }}\bootstrap_tests.bat
      - name: Build PyTorch
        if: ${{ inputs.build_pytorch }}
        run: |
          & ${{ env.SCRIPTS_DIR }}\build_pytorch.bat
      - name: Archive PyTorch
        if: ${{ inputs.build_pytorch }}
        uses: actions/upload-artifact@v4
        with:
          name: pytorch
          path: ${{ env.JOB_DIR }}/pytorch/install/*
          retention-days: 3
      - name: Run tests
        if: ${{ inputs.run_tests }}
        run: |
          & ${{ env.SCRIPTS_DIR }}\test.bat ${{ inputs.run_tests_runs}} ${{ inputs.run_tests_suite }} ${{ inputs.run_tests_filter }}
      - name: Archive test resutls
        if: ${{ always() && inputs.run_tests }}
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: ${{ env.JOB_DIR }}/pytorch/test/test-reports/*
          retention-days: 7
