name: Wipe build cache

on: workflow_dispatch

defaults:
  run:
    shell: cmd

env:
  JOB_DIR: ${{ github.workspace }}\pytorch-unit-tests
  SCRIPTS_DIR: ${{ github.workspace }}\pytorch-unit-tests\workflow\.github\scripts

jobs:
  wipe_build_cache:
    name: Build and run tests
    runs-on: [self-hosted, Windows, ARM64, WASM]
    timeout-minutes: 600
    steps:
      - name: Git checkout workflow
        uses: actions/checkout@v3
        with:
          path: ${{ env.JOB_DIR }}\workflow
      - name: Wipe build cache
        run: ${{ env.SCRIPTS_DIR }}\wipe_pytorch_cache.bat
