name: Wipe runner caches

on: 
  workflow_dispatch:
    inputs:
      wipe_pytorch_sources:
        description: "Wipe PyTorch sources"
        required: false
        default: false
        type: boolean
      wipe_pytorch_build:
        description: "Wipe PyTorch build"
        required: false
        default: false
        type: boolean
defaults:
  run:
    shell: cmd

env:
  JOB_DIR: ${{ github.workspace }}\pytorch-unit-tests
  SCRIPTS_DIR: ${{ github.workspace }}\pytorch-unit-tests\workflow\.github\scripts
  PYTORCH_SOURCES_DIR:  ${{ github.workspace }}\pytorch-unit-tests\pytorch
  PYTORCH_BUILD_DIR:  ${{ github.workspace }}\pytorch-unit-tests\pytorch\build

jobs:
  wipe:
    name: Wipe runner caches
    runs-on: [self-hosted, Windows, ARM64, WASM]
    timeout-minutes: 600
    steps:
      - name: Git checkout workflow
        uses: actions/checkout@v4
        with:
          path: ${{ env.JOB_DIR }}\workflow
      - name: Wipe PyTorch sources
        if: ${{ inputs.wipe_pytorch_sources }}
        run: ${{ env.SCRIPTS_DIR }}\wipe_pytorch_sources.bat
      - name: Wipe PyTorch build
        if: ${{ inputs.wipe_pytorch_build }}
        run: ${{ env.SCRIPTS_DIR }}\wipe_pytorch_build.bat
