name: Wipe runner caches

on: 
  workflow_dispatch:
    inputs:
      is_openblas_sources:
         description: "Enable wipe OpenBLAS sources?"
         required: false
         default: false
         type: boolean
       is_openblas_build:
         description: "Enable wipe OpenBLAS build?"
         required: false
         default: false
         type: boolean
      is_pytorch_sources:
        description: "Enable wipe PyTorch sources?"
        required: false
        default: false
        type: boolean

defaults:
  run:
    shell: cmd

env:
  JOB_DIR: ${{ github.workspace }}\pytorch-job
  SCRIPTS_DIR: ${{ github.workspace }}\pytorch-job\workflow\.github\scripts
  PYTORCH_SOURCES_DIR:  ${{ github.workspace }}\pytorch-job\src
  OPENBLAS_SOURCES_DIR:  ${{ github.workspace }}\pytorch-job\dependencies\openblas
  OPENBLAS_BUILD_DIR:  ${{ github.workspace }}\pytorch-job\dependencies\openblas\build

jobs:
  wipe:
    name: Wipe runner caches
    runs-on: [self-hosted, Windows, ARM64, PYTORCH]
    timeout-minutes: 600
    steps:
      - name: Git checkout workflow
        uses: actions/checkout@v4
        with:
          path: ${{ env.JOB_DIR }}\workflow
      - name: Wipe OpenBLAS build
        if: ${{ inputs.is_openblas_build }}
        run: ${{ env.SCRIPTS_DIR }}\wipe_openblas_build.bat
      - name: Wipe OpenBLAS sources
        if: ${{ inputs.is_openblas_sources }}
        run: ${{ env.SCRIPTS_DIR }}\wipe_openblas_sources.bat      
      - name: Wipe PyTorch sources
        if: ${{ inputs.is_pytorch_sources }}
        run: ${{ env.SCRIPTS_DIR }}\wipe_pytorch_sources.bat