name: Wipe runner caches

on: 
  workflow_dispatch:
    inputs:
      openblas_sources:
        description: "OpenBLAS sources"
        required: false
        default: false
        type: boolean
      openblas_build:
        description: "OpenBLAS build"
        required: false
        default: false
        type: boolean
      pytorch_sources:
        description: "PyTorch sources"
        required: false
        default: false
        type: boolean
      pytorch_build:
        description: "PyTorch build"
        required: false
        default: false
        type: boolean

defaults:
  run:
    shell: cmd

env:
  JOB_DIR: ${{ github.workspace }}\pytorch-job
  SCRIPTS_DIR: ${{ github.workspace }}\pytorch-job\workflow\.github\scripts
  PYTORCH_SOURCES_DIR:  ${{ github.workspace }}\pytorch-job\pytorch
  PYTORCH_BUILD_DIR:  ${{ github.workspace }}\pytorch-job\pytorch\build
  OPENBLAS_SOURCES_DIR:  ${{ github.workspace }}\pytorch-job\openblas
  OPENBLAS_BUILD_DIR:  ${{ github.workspace }}\pytorch-job\openblas\build

jobs:
  wipe:
    name: Wipe runner caches
    runs-on: [self-hosted, Windows, ARM64, PYTORCH]
    timeout-minutes: 600
    steps:
      - name: Git checkout workflow
        uses: actions/checkout@v4
        with:
          path: ${{ env.JOB_DIR }}\workflow
      - name: Wipe OpenBLAS sources
        if: ${{ inputs.openblas_sources }}
        run: ${{ env.SCRIPTS_DIR }}\wipe_openblas_sources.bat
      - name: Wipe OpenBLAS build
        if: ${{ inputs.openblas_build }}
        run: ${{ env.SCRIPTS_DIR }}\wipe_openblas_build.bat
      - name: Wipe PyTorch sources
        if: ${{ inputs.pytorch_sources }}
        run: ${{ env.SCRIPTS_DIR }}\wipe_pytorch_sources.bat
      - name: Wipe PyTorch build
        if: ${{ inputs.pytorch_build }}
        run: ${{ env.SCRIPTS_DIR }}\wipe_pytorch_build.bat
